name = "Mountain-valley Breeze Toy-Model"
description = "Toy model of the mountain-valley breeze."
packages = ["numpy", "matplotlib", "scipy", "/METOYBOX/_static/assets/metoybox-0.0.1-py3-none-any.whl"]